# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('article_name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('id_number', models.AutoField(default=1234, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
