# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adds',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adds',
            name='id_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
